name: Deploy to PythonAnywhere

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Trigger PythonAnywhere Webhook
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "X-Hub-Signature-256: sha256=${{ secrets.WEBHOOK_SECRET }}" \
          -d '{"ref": "refs/heads/main", "repository": {"name": "Roomate-Cost-Splitter"}}' \
          https://hieunguyenhanu.pythonanywhere.com/webhook

