name: Deploy to PythonAnywhere

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  deployments: write
  actions: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://hieunguyenhanu.pythonanywhere.com
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Trigger PythonAnywhere Webhook
      id: webhook
      run: |
        payload='{"ref": "refs/heads/main", "repository": {"name": "Roomate-Cost-Splitter"}}'
        signature=$(echo -n "$payload" | openssl dgst -sha256 -hmac "${{ secrets.WEBHOOK_SECRET }}" | sed 's/^.* //')
        response=$(curl -X POST \
          -H "Content-Type: application/json" \
          -H "X-Hub-Signature-256: sha256=$signature" \
          -d "$payload" \
          https://hieunguyenhanu.pythonanywhere.com/webhook)
        echo "Webhook response: $response"
        
    - name: Deployment Status
      if: success()
      run: |
        echo "✅ Deployed successfully to https://hieunguyenhanu.pythonanywhere.com"

