name: Deploy to PythonAnywhere

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to PythonAnywhere
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PYTHONANYWHERE_HOST }}
        username: ${{ secrets.PYTHONANYWHERE_USERNAME }}
        key: ${{ secrets.PYTHONANYWHERE_SSH_KEY }}
        port: ${{ secrets.PYTHONANYWHERE_SSH_PORT }}
        script: |
          cd ~/Roomate-Cost-Splitter
          git pull origin main
          workon flaskenv
          pip install -r requirements.txt
          touch /var/www/hieunguyenhanu_pythonanywhere_com_wsgi.py

